# Generated by Django 3.1.2 on 2021-07-11 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0131_update_ts_vector_existing_product_name'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='product_pro_search__e78047_gin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_plaintext',
        ),
        migrations.RemoveField(
            model_name='product',
            name='search_vector',
        ),
    ]
