# Generated by Django 3.2.5 on 2021-07-11 22:26

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0132_auto_20210711_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_plaintext',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='digitalcontent',
            index=django.contrib.postgres.indexes.GinIndex(fields=['private_metadata'], name='digitalcontent_p_meta_idx'),
        ),
        migrations.AddIndex(
            model_name='digitalcontent',
            index=django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='digitalcontent_meta_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='product_pro_search__e78047_gin'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['private_metadata'], name='product_p_meta_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='product_meta_idx'),
        ),
    ]
