# Generated by Django 3.1.2 on 2021-07-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0022_auto_20201104_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='token',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='searchable_key',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='token',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
